{{- if .Values.portal.ingress.enabled }}
apiVersion: {{ template "hyperkuber.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "hyperkuber.portal" . }}
  labels: {{- include "hyperkuber.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.portal.ingress.annotations }}
    {{ toYaml .Values.portal.ingress.annotations | indent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.portal.ingress.hostname }}
    - host: {{ .Values.portal.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ template "hyperkuber.portal" . }}
                port:
                  number: 80
    {{- end }}
  {{- if .Values.portal.ingress.tls }}
  tls:
  {{- if .Values.portal.ingress.secretName }}
  - secretName: {{ .Values.portal.ingress.secretName }}
      {{- end }}
    {{- if .Values.portal.ingress.hostname }}
    hosts:
    - {{ .Values.portal.ingress.hostname }}
    {{- end }}
  {{- end }}
{{- end }}