{{- if .Values.portal.ingress.enabled }}
apiVersion: {{ template "hyperkuber.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "hyperkuber.portal" . }}
  labels: {{- include "hyperkuber.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.portal.ingress.annotations }}
    {{ toYaml .Values.portal.ingress.annotations | indent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.portal.ingress.hostname }}
    - host: {{ .Values.portal.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "hyperkuber.portal" . }}
              servicePort: http
    {{- end }}
  {{- if .Values.portal.ingress.tls }}
  tls:
  {{- if .Values.portal.ingress.secretName }}
  - secretName: {{ .Values.portal.ingress.secretName }}
      {{- end }}
    {{- if .Values.portal.ingress.hostname }}
    hosts:
    - {{ .Values.portal.ingress.hostname }}
    {{- end }}
  {{- end }}
{{- end }}