{{- if .Values.portal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperkuber.portal.serviceAccountName" . }}
  labels:
    {{- include "hyperkuber.labels" . | nindent 4 }}
  {{- with .Values.portal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
