site_name: HyperKuber  
theme:
  language: zh
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
  include_sidebar: true

plugins:
  - search
nav:
  - Welcome:
      - Overview: "index.md"
      - Troubleshooting: "troubleshooting.md"
  - Installation:
      - Quick Start: "deploy/manifest.md"
      - Helm Chart: "deploy/helm.md"
      - Operator: "deploy/operator.md"
  - User guide:
      - Hyperkuber License: "user-guide/license.md"
      - Cluster: "user-guide/cluster.md"
  - About us:
      - About: "about.md"
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Chinese
      link: /zh/
      lang: zh