{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hyperkuber.server" . }}
  labels: {{- include "hyperkuber.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
  {{- if .Values.server.persistence }}
  {{- if eq "-" .Values.server.persistence.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}