name: Sync Manifests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'manifests'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cp -rf manifests ${{ runner.temp }}/manifests
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          cp -rf ${{ runner.temp }}/manifests .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add manifests
          git commit --signoff -m "Sync manifests from main"
          git push